pull_request_rules:
  - name: Automatically merge flake update PRs
    conditions:
      - "base=mistress"
      - "-#commits-unverified>0"
      - "#check-success > 0"
      - "#check-failure = 0"
      - "#check-skipped = 0"
      - "#check-pending = 0"
      - "commits[*].email_author = ci_signing+github@ningenkai.soopy.moe"
      - "label=automated"
      - "label=dependencies"
      - "-closed"
    actions:
      delete_head_branch:
        force: false
      merge:
        method: fast-forward
